server:
  port: 8989
spring:
  datasource:
    master:
      url: jdbc:mysql://localhost:3306/test666?useUnicode=true&characterEncoding=UTF-8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 
      type: com.zaxxer.hikari.HikariDataSource
    cluster:
    - key: ds1
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
      idle-timeout: 20000
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 
      type: com.zaxxer.hikari.HikariDataSource
    - key: ds2
      url: jdbc:mysql://localhost:3306/db_app?useUnicode=true&characterEncoding=UTF-8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

logging:
  level:
    com:
      yukong:
        chapter5:
          repository: debug